### ISSUE TITLE
Y24-179 - Move correct labware to the destroyed location even when there is a labware that has failed in the given list

### ISSUE THREAD

**Issue by yoldas** [sanger/asset_audits#629]
**User story**
As an asset audits user I would like to move correct labware to the destroyed location even when there is a labware that has failed in the given list.

**Who are the primary contacts for this story**
Danni, Tris, Seena, Abdullah

**Who is the nominated tester for UAT**
Danni & Tris

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] When the user scans multiple labware,  Destroying labware and Destroying location should allow destruction of all those that pass validation even when some of them fail.
- [ ] There is a message on the page to explain which ones failed and indicate that the others are moved to the destroyed location.

**Dependencies**
This story is blocked by the following dependencies:
N/A

References
This story has a non-blocking relationship with:
- #339 
- #340 
- #650 

**Additional context**
N/A

**Comment by TWJW-SANGER** [comment]
One thought... 

Would it be easier to pre-validate the set of labware to be destroyed?
Such that:
  * Labware selected is checked for any that cannot be destroyed (but nothing is destroyed)
  * User is made aware of the set problematic labware
  * Optionally - user presented with option to destroy the labware that is in the 'good' set.

**Comment by Stan1520** [comment]
New Findings:

I have had the chance to visit the lab with Tris to view, experience and understand the process of destroying labware.

From my understanding (Tris can confirm or add to this), we discussed the challenges and possible solutions for managing and destroying labware (specifically DNA libraries in tubes) that have been stored in a fridge for over two years and are ready for destruction. 

Currently, the team manually checks the dates on tubes to ensure they're over two years old before destroying them. They currently rely on Labwhere for scanning and tracking, but the process is cumbersome, involving manual scanning and error-prone barcode entries.

SOME OF THE PROBLEMS AND "PROPOSED" SOLUTIONS INCLUDE

**Manual Tube Inspection and No Reporting System for Tube Destruction** --- The process of checking whether a tube is over two years old is manual, requiring someone to look at the dates on individual tubes. We think this can be solved by Implementing a system where a report can be generated to show which tubes are over two years old, allowing easier identification for destruction. 

**Inconsistent or Incorrect Scanning and lack of error-checking** --- There are frequent issues with incorrect barcodes being scanned (e.g., wrong length, duplicate entries), causing discrepancies when trying to destroy labware. We think this can be solved by Implementing system-level error checks to prevent incorrect barcode lengths and duplicate entries, ensuring more accurate scanning and tracking. The system should recognize when an odd or incorrect barcode is scanned and prompts users to correct it before finalizing the entry.

**No Date Visibility in the System** --- The dates when tubes were scanned or labeled are not easily visible in the system, forcing workers to physically check tubes in the freezer. We think this can be solved by adding the ability to see the date when a tube was scanned or labeled within the system, so that workers don’t have to manually check dates in the freezer. I have attached a screenshot of labwhere that shows the information of the boxes, there is some space where the dates of the tubes can be included, such that at one glance, we can know what boxes are over 2 years old.

**Discrepancies in Tube Counts** --- Sometimes, the system shows an incorrect count of tubes and locations, which creates confusion during the destruction process. We think this can be solved by developing a script that can search freezer locations to identify boxes containing tubes over two years old, saving time and effort in physically checking tubes.

--------

I am happy to meet and share more light on these issues and proposed solutions. These are based off my experience with the process in the labs and my conversation with Tris.

If we do decide to work with this scope, a bunch of user stories can be created from this findings and all broken down to make the work easier and I am happy to help with that.

> Hi [@SujitDey2022](https://github.com/SujitDey2022), having taken a good look at the codebase and spoken to Abdullah and Seena, this story seems to be much more complex that it initially appears.
> 
> The existing architecture for asset audits is based around an all-or-nothing approach, making a partial submission - as is being proposed in this story - very difficult to implement. At the moment, labware can fail pre-validation checks within Asset Audits, and validation checks in Labwhere and other linked databases, before a final destruction record is created in Asset Audits. Allowing some labware to pass (and be destroyed) while others are prevented from doing so, also raises questions about how to handle the failures from those items that were not able to be destroyed by the system - both from a developer's and user's point of view. These edge cases will make this story hard to implement in a robust manner.
> 
> Would you please check with the primary contacts for this story and confirm the value that it would bring? If we do decide to proceed, we will need to have a finer look at the exact use case that this story addresses and how Asset Audits will need to be refacted to make the implementation maintainable.

**Comment by yoldas** [comment]
Notes from meeting on 25 October:

### Tableau report specific to SeqOps. 2 rooms in Sulston b109 105 and Ogilvie
We talked about reporting. Note that Stanley will talk to Tris about reporting requirements. We would like to know more details about reporting. What would be useful for the user? What filtering would be useful, such as date? We agreed that Tableau Heron reports can be adapted to SeqOps to cover Ogilvie and 2 rooms in Sulston. 

### Check scanned barcodes for duplication and correctness
We talked about incorrect scanning of barcodes, specifically double scanning of the same barcode.

### Close the story Y24-179
We talked about closing the story for partial destruction Y24-179 - Move correct labware to the destroyed location even when there is a labware that has failed in the given list. The user procedure will be to wait until the whole box can be destroyed, which will be easy to see once we have a better reporting.

### Review, update and prioritise DPL-370
We talked about reviewing the existing story created in 2022 to improve the UI. DPL-370 Labware destruction UX improvements.

**Comment by Stan1520** [comment]
**MORE CONSIDERATIONS**
**Tableau report specific to SeqOps. 2 rooms in Sulston b109 105 and Ogilvie**
We talked about reporting. Note that Stanley will talk to Tris about reporting requirements. We would like to know more details about reporting. What would be useful for the user? What filtering would be useful, such as date? We agreed that Tableau Heron reports can be adapted to SeqOps to cover Ogilvie and 2 rooms in Sulston.

Tris has provided a sample of what the report should show
![Image](https://github.com/user-attachments/assets/443d4a0d-a674-485e-a443-d7d1f88e11da)
_I’ve mocked up the above in a .csv file and the NT numbers would obviously be different in each position of a cryo-box.
But something like this would give us a visual tool for each box or location that we could search for – so if we could search a location for example:
Sanger > Ogilvie > AA209 > Sequencing Libraries Freezer 1 > Shelf 1
 
It could pull up a display of all the boxes on a shelf highlighting all those that are >2 yrs old._

**SOME SUGGESTIONS**
**Per-box view of labware ages**
We talked about Tableau reports but the example shown looks like it needs to be done in LabWhere. Maybe - show only the boxes that are ready to be destroyed.
**Using human barcodes (vs machine)**
Our barcodes can be shown in two formats; It is because of the encoding of printed barcodes. The LabWhere DB records machine barcodes and they are passed between AssetAudits, Sequencescape, and LabWhere.

**Comment by SujitDey2022** [comment]
I am closing this story based on the discussion here https://github.com/sanger/asset_audits/issues/629#issuecomment-2444263912 and couple of additional conversations with Tris.

It was determined that in cases where a cryo-box is partially eligible, the decision will be managed at the laboratory level. The lab can choose to wait until the entire box is eligible for destruction or opt to relocate the non-eligible samples and proceed with the destruction of the entire box, as this capability has been recently implemented.

Fyi... @StephenHulme @yoldas @Stan1520
